import { inlineMath } from './math.js';

export function gradientFigure() {
  return `<figure class="gradient-figure"><figcaption>Move the input. Watch the local slope.</figcaption><svg viewBox="0 0 480 280" role="img" aria-label="Curve of x squared with a tangent at the selected input"><defs><clipPath id="gradient-clip"><rect x="40" y="20" width="400" height="220"/></clipPath></defs><path d="M40 240H440M240 20V240" stroke="var(--line)" fill="none"/><g clip-path="url(#gradient-clip)"><path id="gradient-curve" stroke="var(--blue)" stroke-width="3" fill="none"/><path id="gradient-tangent" stroke="var(--mint)" stroke-width="2" stroke-dasharray="7 4" fill="none"/><circle id="gradient-point" r="5" fill="var(--mint)"/></g><text x="40" y="263" fill="var(--muted)">−4</text><text x="237" y="263" fill="var(--muted)">0</text><text x="431" y="263" fill="var(--muted)">4</text><text x="213" y="53" fill="var(--muted)">16</text><text x="220" y="149" fill="var(--muted)">8</text><text x="245" y="232" fill="var(--muted)">0</text></svg><label for="gradient-x">Input x<input id="gradient-x" type="range" min="-4" max="4" step="0.1" value="3"></label><p id="gradient-values" role="status"></p><p class="soft">${inlineMath(String.raw`Read left to right as input and upward as function value. The solid curve is \(f(x)=x^2\); the dashed straight line touches it at the selected point and has slope \(2x\). Near that point, the line approximates the curve; farther away, they separate. Negative tangent values extend below this viewing window. Move the input across zero to see the slope change sign. This analytic illustration updates in the browser; the Python exercise computes the derivative with JAX.`)}</p></figure>`;
}

export function attentionMaskFigure() {
  return `<figure class="attention-lab"><figcaption><h2>Inspect an attention mask</h2><p>Read across a query row to see which keys contribute to its output. Allowed cells show their weights; blocked cells are zero. Every row sums to one, apart from display rounding. Equal weights come from equal allowed scores in this example, not from masking alone.</p></figcaption><div class="attention-controls"><label for="attention-mode">Context boundary<select id="attention-mode"><option value="causal">Causal sequence</option><option value="packed">Two packed examples</option><option value="full">Full context</option></select></label><label for="attention-value">Last value<input id="attention-value" type="range" min="0" max="64" step="1" value="16"></label></div><div id="attention-grid"></div><p id="attention-result" role="status"></p><p class="soft">In causal mode, the nonzero triangle includes the current position and its past. Packed mode splits that triangle into two separate examples, so the second cannot read the first. Full context removes both restrictions. Move the last value and watch which outputs change; the weights stay fixed because this control changes values, not scores. This is an analytic browser calculation; the Python experiments verify the same weighted averages in JAX.</p></figure>`;
}
